### ISSUE TITLE
Make Action Enum Generic

### ISSUE THREAD

**Issue by calebkleveter** [mfxstudios/passport#1]
The [`Verify.Action` enum](https://github.com/mfxstudios/passport/blob/develop/Sources/Passport/Verify.swift#L11-L18) has a case called `success` that takes a type `Any`. I see that you have a todo in there to make that more type-safe. You could probably do that by just making the enum generic with an unconstrained type `T` and have the case type be that.

I also suggest changing the value's label, as you won't always have a user type stored in it:

```swift
extension Verify {
    public enum Action<T> {
        case success(payload: T)
        case fail(status: HTTPStatus)
        case redirect(path: String, type: RedirectType)
        case pass
    }
}
```

**Comment by Prince2k3** [comment]
done!
